-- Milinov Jewelry: inventario, administradores, fotos y tiempo real.
-- Ejecutar en Supabase > SQL Editor antes de seed.sql.

create table if not exists public.products (
  id          bigint generated by default as identity primary key,
  sku         text,
  gender      text not null check (gender in ('Hombre', 'Mujer')),
  name        text not null,
  category    text,
  collection  text,
  model       text,
  material    text,
  price       numeric not null check (price > 0),
  old_price   numeric check (old_price is null or old_price > price),
  stock       integer not null default 0 check (stock >= 0),
  status      text not null default 'active' check (status in ('active', 'draft', 'sold_out')),
  badge       text,
  size_mm     text,
  weight_g    numeric,
  care        text,
  warranty    text,
  featured    boolean not null default false,
  image       text,
  images      jsonb not null default '[]'::jsonb,
  description text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table public.products add column if not exists updated_at timestamptz not null default now();

create unique index if not exists products_sku_key
  on public.products (lower(sku)) where sku is not null and sku <> '';

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.admin_users enable row level security;

-- Los proyectos nuevos ya no exponen tablas automáticamente al Data API.
revoke all on public.products from anon, authenticated;
revoke all on public.admin_users from anon, authenticated;
revoke all on sequence public.products_id_seq from anon, authenticated;
grant usage on schema public to anon, authenticated;
grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;
grant usage, select on sequence public.products_id_seq to authenticated;
grant select on public.admin_users to authenticated;

drop policy if exists "lectura_publica_activos" on public.products;
drop policy if exists "lectura_publica_catalogo" on public.products;
create policy "lectura_publica_catalogo" on public.products
  for select
  to anon, authenticated
  using (status in ('active', 'sold_out'));

drop policy if exists "escritura_autenticados" on public.products;
drop policy if exists "administradores_ven_todo" on public.products;
create policy "administradores_ven_todo" on public.products
  for select
  to authenticated
  using (exists (
    select 1 from public.admin_users a where a.user_id = (select auth.uid())
  ));

drop policy if exists "administradores_crean" on public.products;
create policy "administradores_crean" on public.products
  for insert
  to authenticated
  with check (exists (
    select 1 from public.admin_users a where a.user_id = (select auth.uid())
  ));

drop policy if exists "administradores_actualizan" on public.products;
create policy "administradores_actualizan" on public.products
  for update
  to authenticated
  using (exists (
    select 1 from public.admin_users a where a.user_id = (select auth.uid())
  ))
  with check (exists (
    select 1 from public.admin_users a where a.user_id = (select auth.uid())
  ));

drop policy if exists "administradores_eliminan" on public.products;
create policy "administradores_eliminan" on public.products
  for delete
  to authenticated
  using (exists (
    select 1 from public.admin_users a where a.user_id = (select auth.uid())
  ));

drop policy if exists "administrador_ve_su_acceso" on public.admin_users;
create policy "administrador_ve_su_acceso" on public.admin_users
  for select
  to authenticated
  using (user_id = (select auth.uid()));

-- Bucket público para que las fotos carguen rápido en el catálogo. Solo los
-- administradores autenticados pueden subir, reemplazar o borrar archivos.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('productos', 'productos', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "fotos_publicas" on storage.objects;
create policy "fotos_publicas" on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'productos');

drop policy if exists "administradores_suben_fotos" on storage.objects;
create policy "administradores_suben_fotos" on storage.objects
  for insert
  to authenticated
  with check (bucket_id = 'productos' and exists (
    select 1 from public.admin_users a where a.user_id = (select auth.uid())
  ));

drop policy if exists "administradores_actualizan_fotos" on storage.objects;
create policy "administradores_actualizan_fotos" on storage.objects
  for update
  to authenticated
  using (bucket_id = 'productos' and exists (
    select 1 from public.admin_users a where a.user_id = (select auth.uid())
  ))
  with check (bucket_id = 'productos' and exists (
    select 1 from public.admin_users a where a.user_id = (select auth.uid())
  ));

drop policy if exists "administradores_borran_fotos" on storage.objects;
create policy "administradores_borran_fotos" on storage.objects
  for delete
  to authenticated
  using (bucket_id = 'productos' and exists (
    select 1 from public.admin_users a where a.user_id = (select auth.uid())
  ));

-- Habilita eventos INSERT/UPDATE/DELETE para refrescar tienda y panel.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'products'
  ) then
    alter publication supabase_realtime add table public.products;
  end if;
end $$;

-- Después de crear tu usuario en Authentication > Users, autorízalo una vez:
-- insert into public.admin_users (user_id)
-- select id from auth.users where email = 'TU_CORREO';
