-- ============================================================
-- Milinov Jewelry — Esquema de la base de datos en Supabase
-- Ejecuta este script en: Supabase → SQL Editor → New query → Run
-- Luego corre seed.sql para cargar los productos de ejemplo.
-- ============================================================

create table if not exists public.products (
  id          bigint generated by default as identity primary key,
  sku         text,
  gender      text not null check (gender in ('Hombre', 'Mujer')),
  name        text not null,
  category    text,
  collection  text,
  model       text,
  material    text,
  price       numeric not null check (price > 0),
  old_price   numeric check (old_price is null or old_price > price),
  stock       integer not null default 0 check (stock >= 0),
  status      text not null default 'active' check (status in ('active', 'draft', 'sold_out')),
  badge       text,
  size_mm     text,
  weight_g    numeric,
  care        text,
  warranty    text,
  featured    boolean not null default false,
  image       text,
  images      jsonb not null default '[]'::jsonb,
  description text,
  created_at  timestamptz not null default now()
);

-- El SKU, si se usa, debe ser único.
create unique index if not exists products_sku_key
  on public.products (lower(sku)) where sku is not null and sku <> '';

-- ============================================================
-- Seguridad a nivel de fila (RLS)
-- ============================================================
alter table public.products enable row level security;

-- Lectura PÚBLICA solo de productos activos (lo que ve la tienda con la anon key).
drop policy if exists "lectura_publica_activos" on public.products;
create policy "lectura_publica_activos" on public.products
  for select
  using (status = 'active');

-- Escritura solo para usuarios AUTENTICADOS (tú, desde el panel de Supabase
-- o una app con login). La anon key del sitio NO puede escribir.
drop policy if exists "escritura_autenticados" on public.products;
create policy "escritura_autenticados" on public.products
  for all
  to authenticated
  using (true)
  with check (true);
