-- ============================================================
-- Migración 1/3 — Inventario Milinov: tablas, constraints, triggers,
-- índices, grants mínimos y políticas RLS.
-- Diseño y alternativas: docs/agent/DESIGN-ADMIN-INVENTARIO.md (D1–D4).
--
-- Contexto verificado (docs oficiales, 2026-08-11): los proyectos nuevos de
-- Supabase NO exponen tablas al Data API sin GRANT explícito (cambio del
-- 2026-05-30), por eso los grants de abajo son la lista completa y deliberada.
-- ============================================================

-- ------------------------------------------------------------
-- Función de validación: la galería debe ser un arreglo JSON de textos
-- no vacíos. Se usa en un CHECK, por eso es IMMUTABLE.
--
-- Se deja con EXECUTE para PUBLIC a propósito: Postgres comprueba el permiso
-- de las funciones usadas en un CHECK contra el rol que inserta, así que
-- revocarlo rompería las escrituras del panel (verificado). Es una función
-- pura sobre el valor que el propio llamante envía: no lee datos ni los expone.
-- ------------------------------------------------------------
create or replace function public.es_arreglo_de_textos(value jsonb)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select jsonb_typeof(value) = 'array'
     and not exists (
       select 1
       from jsonb_array_elements(value) as e(elemento)
       where jsonb_typeof(e.elemento) <> 'string'
          or btrim(e.elemento #>> '{}') = ''
     )
$$;

-- ------------------------------------------------------------
-- Tabla principal del inventario
-- ------------------------------------------------------------
create table public.products (
  id          bigint generated by default as identity primary key,
  sku         text not null,
  gender      text not null check (gender in ('Hombre', 'Mujer')),
  name        text not null check (btrim(name) <> ''),
  category    text,
  collection  text,
  model       text,
  material    text,
  price       numeric not null check (price > 0),
  old_price   numeric,
  stock       integer not null default 0 check (stock >= 0),
  status      text not null default 'draft' check (status in ('active', 'draft', 'sold_out')),
  badge       text check (badge is null or badge in ('', 'nuevo', 'bestseller')),
  size_mm     text,
  weight_g    numeric check (weight_g is null or weight_g > 0),
  care        text,
  warranty    text,
  featured    boolean not null default false,
  image       text,
  images      jsonb not null default '[]'::jsonb,
  description text,
  -- Concurrencia optimista (D1): el panel envía la versión que leyó; el
  -- trigger la incrementa en cada UPDATE. 0 filas afectadas = conflicto.
  version     integer not null default 1 check (version >= 1),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  -- SKU siempre obligatorio (D4); la unicidad case-insensitive es un índice aparte.
  constraint products_sku_no_vacio check (btrim(sku) <> ''),

  -- El precio tachado solo tiene sentido si es mayor al precio vigente.
  constraint products_precio_anterior_mayor check (old_price is null or old_price > price),

  -- La galería siempre es un arreglo JSON de textos (D3).
  constraint products_images_arreglo check (public.es_arreglo_de_textos(images)),

  -- Un producto activo debe tener stock (D2); agotado/borrador admiten 0.
  constraint products_activo_con_stock check (status <> 'active' or stock > 0),

  -- Publicado (active/sold_out) exige taxonomía completa y >= 1 foto (D3, D4).
  constraint products_publicado_completo check (
    status = 'draft' or (
      btrim(coalesce(category, '')) <> ''
      and btrim(coalesce(material, '')) <> ''
      and btrim(coalesce(model, '')) <> ''
      and jsonb_typeof(images) = 'array'
      and jsonb_array_length(images) >= 1
    )
  ),

  -- La portada es siempre la primera foto de la galería; sin galería no hay portada (D3).
  -- `image is not null` es imprescindible: un CHECK que evalúa a NULL se
  -- considera satisfecho, así que sin esa condición una joya publicada podía
  -- guardarse con galería llena y portada vacía.
  constraint products_portada_coherente check (
    case
      when jsonb_typeof(images) = 'array' and jsonb_array_length(images) >= 1
        then image is not null and image = images ->> 0
      else coalesce(image, '') = ''
    end
  )
);

-- Unicidad de SKU sin distinguir mayúsculas (D4).
create unique index products_sku_unico on public.products (lower(sku));

-- Índices para los filtros del panel y la tienda.
create index products_estado_idx     on public.products (status);
create index products_categoria_idx  on public.products (category);
create index products_material_idx   on public.products (material);
create index products_genero_idx     on public.products (gender);
create index products_destacados_idx on public.products (featured) where featured;

-- ------------------------------------------------------------
-- Trigger: normaliza SKU y mantiene updated_at + version (D1).
-- El valor de version que envíe el cliente se ignora: siempre old + 1.
-- ------------------------------------------------------------
create or replace function public.products_mantener_fila()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.sku := btrim(new.sku);
  if tg_op = 'UPDATE' then
    new.updated_at := now();
    new.version := old.version + 1;
  else
    -- La versión la administra la base: un cliente no puede sembrar la suya.
    new.version := 1;
  end if;
  return new;
end;
$$;

create trigger products_mantener_fila
  before insert or update on public.products
  for each row execute function public.products_mantener_fila();

-- ------------------------------------------------------------
-- Administradoras autorizadas. Sin políticas de escritura ni grants de
-- escritura: las altas/bajas se hacen solo desde el SQL Editor por la dueña
-- del proyecto. Borrar una fila corta el acceso a datos al instante porque
-- todas las políticas la consultan por petición.
-- ------------------------------------------------------------
create table public.admin_users (
  user_id    uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- RLS + grants mínimos (deny by default).
-- ------------------------------------------------------------
alter table public.products    enable row level security;
alter table public.admin_users enable row level security;

revoke all on public.products    from anon, authenticated;
revoke all on public.admin_users from anon, authenticated;

grant usage on schema public to anon, authenticated;
grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;
grant select on public.admin_users to authenticated;

-- La secuencia de la columna identity necesita grant para los INSERT del panel.
do $$
begin
  execute format(
    'grant usage, select on sequence %s to authenticated',
    pg_get_serial_sequence('public.products', 'id')
  );
end $$;

-- Lectura pública del catálogo: SOLO para anon (no referencia admin_users,
-- así anon nunca toca una tabla sobre la que no tiene grant).
create policy "lectura_publica_catalogo" on public.products
  for select
  to anon, authenticated
  using (status in ('active', 'sold_out'));

-- Las administradoras ven todo, incluidos borradores.
-- Nota deliberada: dos políticas SELECT permisivas conviven (advisor 0006 =
-- WARN aceptado); unificarlas obligaría a dar a anon acceso a admin_users.
create policy "administradoras_ven_todo" on public.products
  for select
  to authenticated
  using (exists (
    select 1 from public.admin_users a where a.user_id = (select auth.uid())
  ));

create policy "administradoras_crean" on public.products
  for insert
  to authenticated
  with check (exists (
    select 1 from public.admin_users a where a.user_id = (select auth.uid())
  ));

create policy "administradoras_actualizan" on public.products
  for update
  to authenticated
  using (exists (
    select 1 from public.admin_users a where a.user_id = (select auth.uid())
  ))
  with check (exists (
    select 1 from public.admin_users a where a.user_id = (select auth.uid())
  ));

create policy "administradoras_eliminan" on public.products
  for delete
  to authenticated
  using (exists (
    select 1 from public.admin_users a where a.user_id = (select auth.uid())
  ));

-- Cada cuenta solo puede ver su propia fila de autorización.
create policy "administradora_ve_su_acceso" on public.admin_users
  for select
  to authenticated
  using (user_id = (select auth.uid()));
